# Generated by Django 5.0.1 on 2024-01-10 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nba_id', models.IntegerField()),
                ('last_name', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField()),
                ('has_image', models.BooleanField()),
            ],
        ),
    ]
