# Generated by Django 5.0.1 on 2024-01-10 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba_play', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='id',
        ),
        migrations.AlterField(
            model_name='player',
            name='nba_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
