# Generated by Django 5.0.1 on 2024-01-10 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nba_play', '0002_remove_player_id_alter_player_nba_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='player',
            table='players',
        ),
    ]
