# Generated by Django 5.0.1 on 2024-01-10 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba_play', '0003_alter_player_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerImage',
            fields=[
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='image', serialize=False, to='nba_play.player')),
                ('has_image', models.BooleanField()),
            ],
            options={
                'db_table': 'player_images',
            },
        ),
        migrations.RemoveField(
            model_name='player',
            name='has_image',
        ),
    ]
